export default [
  {
    id: "recNXOx9Cc2StqgSD",
    fields: {
      "Last Name": "Knight",
      "First Name": "David",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Department of Forest and Rangeland Stewardship"],
      "Research Focus": "Wetland ecology (Canada, Peru, Poland)",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recZoZlN29YUmVV4p",
    fields: {
      "Last Name": "Kobayashi",
      "First Name": "Yasuto",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1992",
    },
    createdTime: "2021-09-02T13:55:20.000Z",
  },
  {
    id: "rec7plLTv8KagnOuc",
    fields: {
      "Last Name": "Koelin",
      "First Name": "Gail",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T13:55:49.000Z",
  },
  {
    id: "recUZAwM1YOzIalHK",
    fields: {
      "Last Name": "Kreidenweis",
      "First Name": "Sonia",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Atmospheric Science"],
      "Research Focus":
        "Atmospheric chemistry; aerosol chemistry and physics; thermodynamics and cloud physics; air pollution",
      "Spatial Angle": "Atmospheric chemistry - cloud physics - air pollution",
      "Story Theme": "Environment",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recpaKWXW6hzsP00U",
    fields: {
      "Last Name": "Kroll",
      "First Name": "Stephan",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Agricultural and Resource Economics"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recSF2jDnhDCesPvS",
    fields: {
      "Last Name": "Kuppuswamy",
      "First Name": "Raja",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T13:55:53.000Z",
  },
  {
    id: "recno4UCfxZ5n1zPy",
    fields: {
      "Last Name": "Kwiatkowski",
      "First Name": "Lynn",
      "College/Division": ["College of Liberal Arts"],
      "Unit/Program": [
        "Anthropology \\ Global Health",
        "Gender Violence",
        "International Development",
        "Southeast Asia",
      ],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recb39NeYN5z8LSWB",
    fields: {
      "Last Name": "Laituri",
      "First Name": "Melinda",
      "StoryMap Link": "https://arcg.is/1uibjW",
      "Production Phase": "Story Edits",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Ecosystem Science and Sustainability"],
      "Research Focus": "Secondary Cities - Global ",
      "Story Title": "Geospatial Technologies",
      Tagline: "The bond between science and societies",
      "Research Blurb":
        "The Geospatial Centroid in the Morgan Library at CSU, directed by professor Melinda Laituri, serves a dual role. CSU faculty and students can use a multitude of GIS programs through the Centroid to map and analyze data across disciplines and for a variety of purposes — vegetation cover, population growth, animal migration. But Dr. Laituri also wants the Centroid to be an educational tool, promoting critical thinking around how to use tools like GIS properly, and both what can and cannot be learned from technology.",
      "Blurb Author": "JF",
      "Spatial Angle":
        "Let's work with Laituri on this and perhaps showcase one of the Secondary Cities Interactive maps that she has developed.",
      "Story Theme": "Community",
      "Institutional/Program Stories": [
        "rechYc6m71NDqJXH9",
        "reczq7bBll5BU3KvI",
      ],
      "Production Round": "Round 1",
      "Story Assets": ["Find Existing Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "Career Pathway ": ["Geographer"],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/En_m1RmA34pCjmb482eE6vgBaif-eKOHk-4bB1kgiY8m5A?e=lGgrgo",
      "StoryMap VIEW Link":
        "https://storymaps.arcgis.com/stories/15fef678626d4f589ef0aa7090f67369",
      "Story Card Image": [
        {
          id: "attTyo2yhfrf18Uu8",
          width: 4928,
          height: 3280,
          url: "https://dl.airtable.com/.attachments/a794671268b9c789f95cc12cf5798097/df2d631d/nasa-_SFJhRPzJHs-unsplash1.jpg",
          filename: "nasa-_SFJhRPzJHs-unsplash (1).jpg",
          size: 4146512,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/47498d949b94f7a62fa7d7859ed8015f/91ddf51a",
              width: 54,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/a2ae002ab1f7c9c91083e204fce1b8df/3895203e",
              width: 769,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/9c3910c2235105e4e3f10267157ded2b/85c90371",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      "Pop-Up Card Content":
        "By 2030, almost 60% of the world’s population will live in urban areas...and 95% of urban expansion in the next decades will take place in the developing world.",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "reciuxP6MFLww2olD",
    fields: {
      "Last Name": "Large",
      "First Name": "Leonard",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2008",
    },
    createdTime: "2021-09-02T13:56:04.000Z",
  },
  {
    id: "rectphgFIT8YrKKa2",
    fields: {
      "Last Name": "Leach",
      "First Name": "Jan",
      "StoryMap Link": "https://arcg.is/08X9Lv",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Agricultural Biology"],
      "Research Focus": "Plant Pathogens - China and the Philippines ",
      "Story Title": "Revolutionizing agriculture",
      Tagline: "Combating world hunger one grain of rice at a time",
      "Research Blurb":
        "Dr. Jan Leach, associate dean for research and professor of Bioagricultural Sciences and Pest Management in the College of Agricultural Sciences at CSU, combats world hunger one grain of rice at a time. Defending one of the world's most important food crops from the ravages of pests and climate change, driven by a strong sense of purpose in her work, Leach partners closely with rice growers and scientific collaborators in the Philippines and worldwide. She believes collaboration is key to protecting the food that sustains most of the developing world.",
      "Blurb Author": "CN",
      LAT: " ",
      "Story Theme": "Food",
      "Institutional/Program Stories": [
        "recQCiv7n0YhrDl65",
        "rec0scLExpYcBzVhl",
      ],
      "Production Round": "Round 1",
      "Grand Challenge": ["Climate Change"],
      "Story Assets": ["TBD"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/ElmDBSSggzdGtzygRTFXbWQB2zbH3u579mLGpkFOzP5rrw?e=edar4n",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recToAxUZLwoSiyHd",
    fields: {
      "Last Name": "Levalley",
      "First Name": "Stephen",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Animal Sciences"],
      "Research Focus":
        "Lazareuskoye Joint Stock Farm , Russia, Identified as leading American Sheep Expert by the Russian Company paid travel to on site",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recLZfyBcUyVUBfJ8",
    fields: {
      "Last Name": "Li",
      "First Name": "Kaigang",
      Institution: "Fort Collins",
      "College/Division": ["Health and Human Sciences"],
      "Unit/Program": ["Health and Exercise Science"],
      "Research Focus":
        "Working with the China Institute of Sport Science in Beijing centered around novel approaches to understanding the barriers to physical activity and facilitating a physically active lifestyle to enhance the overall health of the public.",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Story Theme": "Health",
      "International/Institutional Partners": ["recehdSQz21L7MXzz"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recSfOcLJ27VDRNzF",
    fields: {
      "Last Name": "Linke",
      "First Name": "Lyndsey",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "reclEFO02f0FAGsMI",
    fields: {
      "Last Name": "MacDonald",
      "First Name": "John",
      "StoryMap Link": "https://arcg.is/1y8W0X",
      "Production Phase": "Drafting",
      Institution: "Fort Collins",
      "College/Division": ["Business"],
      "Unit/Program": ["Management"],
      "Research Focus": "Illegal Wildlife Trade - West Africa",
      "Story Title": "Follow the Money",
      Tagline: "Dismantling the supply chains of wildlife trafficking",
      "Research Blurb":
        "Supply chain management is usually used to build up a business, but CSU professor John McDonald wants to use supply chain management to bring down wildlife-destroying criminals. McDonald’s work in Africa is centered in Sri Lanka. Illegal wildlife trafficking generates an estimated $23 billion each year in the worldwide criminal economy. Thriving illegal businesses, just like legal ones, have a steady — and often complicated — integrated flow of purchasing and distribution operations. Disrupting the supply chain can kill the business. Understanding the supply chain of wildlife trafficking may be able to help slow the crime and prosecute criminals.",
      "Blurb Author": "MH",
      LAT: "8",
      LONG: "77",
      "Story Theme": "Environment",
      "Production Round": "Round 1",
      "Story Assets": ["TBD"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "Career Pathway ": ["Supply Chain Professional"],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/Ek-zTlqcM1dPgyXjoyPnCqsBcUyI7oEsDx4Zqr5T3Zw9FQ?e=NMZkDp",
      "StoryMap VIEW Link":
        "https://storymaps.arcgis.com/stories/04ecb54cb3be4a99828b0f52493e9133",
      "Story Card Image": [
        {
          id: "attLIn03V44jfecYb",
          width: 6000,
          height: 3376,
          url: "https://dl.airtable.com/.attachments/7066efb6e96ed4c0b8139302d354d7e9/c2647a85/louis-mornaud-mtTpAM2uaRM-unsplash.jpg",
          filename: "louis-mornaud-mtTpAM2uaRM-unsplash.jpg",
          size: 1927812,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/f8847deb900d5e552de172ac575f44c7/69e39f44",
              width: 64,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/583658bb938cbd080052bd43095ea21d/cff43585",
              width: 910,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/ebeb523543b47fc3877b5a19974072b5/81d739e6",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      "Pop-Up Card Content":
        "Illegal wildlife trafficking generates an estimated $23 billion each year in the worldwide criminal economy.",
      "Pop-Up Card Image": [
        {
          id: "attDB1LPpHEol3MFg",
          width: 2963,
          height: 3951,
          url: "https://dl.airtable.com/.attachments/87316740e711e07a8c4a0da4336ba940/33aadeb6/arno-senoner-yqu6tJkSQ_k-unsplash.jpg",
          filename: "arno-senoner-yqu6tJkSQ_k-unsplash.jpg",
          size: 2011726,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/73f635a719c243546d4eb4f147fd4c3a/0c9d69db",
              width: 27,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/303a7ef92f0036839d4c4b96edf70a6f/4a20f37e",
              width: 512,
              height: 683,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/397244e001d5af5cfbbc6f3505ed00b7/662cf45c",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recYX7CjnPWoyAgeU",
    fields: {
      "Last Name": "MacDonald",
      "First Name": "John",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T13:56:20.000Z",
  },
  {
    id: "recjaLKDCBA70gUej",
    fields: {
      "Last Name": "Maciejewski",
      "First Name": "Tony",
      "College/Division": ["Walter Scott", "Jr. College of Engineering"],
      "Unit/Program": ["ECE"],
      "Research Focus":
        "educational and research collaborations with the director of the Engineering Design Initiative Lab, Constanza Miranda, at the Catholic University of Chile in Santiago. Also CEE faulty have ties ot this University",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "rece7UGlVQcTn8RvL",
    fields: {
      "Last Name": "MacNeill",
      "First Name": "Amy",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Microbiology, Immunology, and Pathology"],
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Story Theme": "Health",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "reckCE967ddVoQ4cP",
    fields: {
      "Last Name": "Mahmoud",
      "First Name": "Hussam",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Civil and Environmental Engineering"],
      "Story Theme": "Community",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recrm1cVCTQg21TWE",
    fields: {
      "Last Name": "Malin",
      "First Name": "Stephanie",
      "StoryMap Link": "https://arcg.is/11OG1f",
      Institution: "Fort Collins",
      "College/Division": ["Liberal Arts"],
      "Unit/Program": ["Sociology"],
      "Story Title": "The Price of Nuclear Power",
      Tagline: " Studying energy production and environmental justice",
      "Research Blurb":
        "The world’s population is expected to exceed 9 billion by 2050. With this growth will come heightened demand for clean water, healthy food, manufactured goods, and abundant energy — all requiring accelerated natural resource development and extraction. Stephanie Malin, environmental sociology professor and founding member of the Center for Environmental Justice at CSU, researches the impacts and outcomes of energy production and globalization on the health and sustainability of Earth’s finite ecosystems, resources, and communities. In her book, The Price of Nuclear Power: Uranium Communities and Environmental Justice, Malin asks whether nuclear power provides a socially sustainable solution in the age of climate change mitigation, exploring the intersection of legacy uranium mining and current efforts to renew uranium production at sites such as the Piñon Ridge Uranium Mill in western Colorado.",
      "Blurb Author": "CRM",
      "Centroid Mapper": "Kristin Karashinski (2021-2022)",
      "Spatial Angle":
        "Map of Oil and Gas infastrucutre in Colorado that brings together population growth and water somehow. ",
      LAT: " ",
      "Story Theme": "Energy",
      "Institutional/Program Stories": ["recgh0HXJG2zMUgpR"],
      "Story Tags": ["Environmental Justice"],
      "Production Round": "Round 1",
      "Grand Challenge": ["Climate Change"],
      "Story Assets": ["Interactive Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/Ev97qJJfqr1Pk6zhSthtJQYBkwCSFICm1Tb3OsgD_Nmulw?e=vRa9oF",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recGVeHBXiUg6b3h3",
    fields: {
      "Last Name": "Manning",
      "First Name": "Dale",
      "StoryMap Link": "https://arcg.is/1TzOiO1",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Agricultural and Resource Economics"],
      "Research Focus": "Food, water, energy - Uganda",
      "Story Title": "Owning Their Power",
      Tagline: "Economically sustainable futures for rural villages",
      "Research Blurb":
        "Approximately 16% of the world’s population (1.2 billion people) lives without electricity, imposing a major barrier to participating in today’s economy. Dale Manning and the Smart Village Microgrid Laboratory seek to test and install energy microgrids in rural Rwandan communities to provide local and sustainable sources of electricity for years to come. To achieve village-level electrification, the CSU Energy Institute is working with the University of Rwanda to build mirrored microgrid labs at both locations to facilitate continued collaboration between the two institutions.",
      "Blurb Author": "AF",
      "Spatial Angle":
        'World at night map with Rwandan boundary overlayed...or how can we play with light in the map? How can we look at access to power around the world, and in Rwanda specifically, by "lighting up the map"?',
      LAT: " ",
      "Story Theme": "Energy",
      "Institutional/Program Stories": ["recz5lIQrJxWz00es"],
      "International/Institutional Partners": ["rec7iBHneazdiZVxC"],
      "Production Round": "Round 1",
      "Grand Challenge": ["Climate Change"],
      "Story Assets": ["Interactive Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/ElcwnTf31vZKgX4_NmdQTMcBL_YCJazk0YguFTI2XrfUIA?e=1bDDlT",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recDk9ne1bfZa88qH",
    fields: {
      "Last Name": "Marchese",
      "First Name": "Anthony",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Mechanical Engineering"],
      "Research Focus":
        "Solar Cooling for Horticulture Preservation (Mozambique)",
      "Story Theme": "Energy",
      "Story Tags": ["Development/Innovation"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recAsmXZHzUnG5sZe",
    fields: {
      "Last Name": "Martinez",
      "First Name": "Doreen",
      "College/Division": ["OneHealth"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "reco1MBFvwGnWhIlg",
    fields: {
      "Last Name": "Mathiason",
      "First Name": "Candace",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Microbiology, Immunology, and Pathology"],
      "Research Blurb":
        "Sometimes referred to coloquially as \"zombie deer disease,\" chronic wasting disease (CWD) is a prion disease affecting deer, elk, reindeer, and moose. While the exact mechanisms aren't fully understood, prions -- misfolded proteins -- cause neurons to degenerate by forming plaques in the central nervous system. As neurons die, holes are formed in the brain and other neural tissue, leading to dramatic weight loss, listlessness, trouble walking, and eventually death. While there has never been a reported case of CWD in humans, a jump to humans is not outside of the realm of possibility. And humans already experience other protein-misfolding diseases such as Alzheimer's, Parkinson's, and diabetes. CSU's Candace Mathiason is a leading researcher in the area of prions -- while working on her Ph.D., she demonstrated for the first time that prions are carried in bodily fluids and can be transmitted without direct bodily contact -- and hopes that her research into mechanisms of transmission can shed light on not just CWD, but a wide range of neurodegenerative diseases. ",
      "Blurb Author": "JF",
      "Story Theme": "Health",
      "ID Tags": ["Alumnus"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recLCnNqg2i21De5V",
    fields: {
      "Last Name": "Matushima",
      "First Name": "John",
      "StoryMap Link": "https://arcg.is/4mrm40",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Animal Sciences"],
      "Research Focus": "Japan (Photos in email from M. Sweitzer--Cara)",
      "Story Theme": "Food",
      "ID Tags": ["Alumnus"],
      "Production Round": "Alumni Round",
      Year: "1943, 1945",
      Degree: ["BS", "MS"],
    },
    createdTime: "2021-09-02T13:56:47.000Z",
  },
  {
    id: "rec0WR0ke2tgQqqNK",
    fields: {
      "Last Name": "Mayo",
      "First Name": "Christie",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "rec7lUuvPW0HiTjw8",
    fields: {
      "Last Name": "McCornick",
      "First Name": "Peter",
      "Research Focus":
        "Scottish, Leads Daughtery Water Center out of University of Nebraska",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus", "International"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T13:58:20.000Z",
  },
  {
    id: "recQoPnddh0Kveffh",
    fields: {
      "Last Name": "McGrath",
      "First Name": "Daniel",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Department of Geosciences"],
      "Research Focus": "Glaciology, hydrology (Antarctica, Patagonia)",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "rechb2Mu1560lTfHi",
    fields: {
      "Last Name": "Mcivor",
      "First Name": "David",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Department of Human Dimensions of Natural Resources"],
      "Research Focus": "International ecotourism",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recJTKzLO56j6ZvID",
    fields: {
      "Last Name": "Melby",
      "First Name": "Chris",
      "StoryMap Link": "https://arcg.is/8zvzq",
      Institution: "Fort Collins",
      "College/Division": ["Health and Human Sciences"],
      "Unit/Program": ["Food Science and Human Nutrition"],
      "Research Focus": "Nutrition and Diet - Ecuador",
      "Story Title": "Precarious Dietary Patterns",
      Tagline: "Balancing agricultural and nutritional diversity",
      "Research Blurb":
        'In developing countries like Ecuador, as populations shift from rural to urban areas, diets often shift from traditional, grain- and vegetable-based fare to a more Western diet, high in sugar and fat. Professor Chris Melby with the Colorado School of Public Health at CSU studies how nutrition — and lack of access to diverse, healthy, nutritious foods — contributes to the chances of having a life-changing illness like stroke, heart disease, or diabetes. Melby is working with colleagues and graduate students in Ecuador to study how to help communities navigate this "nutrition transition," maximizing dietary diversity and minimizing risks for malnutrition and obesity.',
      "Blurb Author": "CN",
      "Spatial Angle":
        "human migration; increase in health outcomes; rural diets and urban diets",
      "Story Theme": "Food",
      "ID Tags": ["Alumnus", "First Generation"],
      "Production Round": "Round 1",
      Year: "1973",
      Degree: ["BS"],
      "Story Assets": ["Interactive Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EgGNrUvK-g1JmtqbJmkbobUB7R5yxD6FUC5sS9wBNafs_w?e=fL4VO8",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "reczhPphF5CJrMyls",
    fields: {
      "Last Name": "Metcalf",
      "First Name": "Jessica",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Animal Sciences"],
      "Research Focus": "CIFAR Global Scholar",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recOYd9cuYrcX9h56",
    fields: {
      "Last Name": "Miller",
      "First Name": "Steven",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Atmospheric Science"],
      "Spatial Angle": "Atmospheric Science",
      "Story Theme": "Environment",
      "ID Tags": ["Alumnus"],
      "Institutional/Program Stories": ["recmfw9UFACO660S8"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rechErQdd1sO0xY7c",
    fields: {
      "Last Name": "Minas",
      "First Name": "Ioannis",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Horticulture and Landscape Architecture"],
      "Research Focus":
        "NC-140 Rootstock Research Trial Coordination, International Fruit Tree Association",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recQflUVzqayxe4hr",
    fields: {
      "Last Name": "Mitchell",
      "First Name": "Rob",
      "College/Division": ["College of Business"],
      "Unit/Program": ["Social enterprise / start-ups"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recuQK9VnpXWWFno9",
    fields: {
      "Last Name": "Mizukami",
      "First Name": "Kimiharu",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1992",
    },
    createdTime: "2021-09-02T13:59:30.000Z",
  },
  {
    id: "recBVlYVhbRDvo22S",
    fields: {
      "Last Name": "Mohr",
      "First Name": "Gina",
      "College/Division": ["College of Liberal Arts"],
      "Unit/Program": [
        "Political Science \\ North Africa and Middle East",
        "Social Policy and Politics of Food",
      ],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recfuvzfgBEoTBHG9",
    fields: {
      "Last Name": "Mueller",
      "First Name": "Nathan",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Soil and Crop Sciences"],
      "Research Focus":
        "Agricultural sustainability and climate change impacts/adaptation; spatial data science and modeling",
      "Story Theme": "Environment",
      "Story Tags": ["Agricultural Sustainability"],
      "Production Round": "Round 2",
      "Grand Challenge": ["Climate Change"],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recYT9HzlaYP8t413",
    fields: {
      "Last Name": "Nakahara",
      "First Name": "Yoshio",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1987",
    },
    createdTime: "2021-09-02T14:00:37.000Z",
  },
  {
    id: "rec58TOSnphwj0d22",
    fields: {
      "Last Name": "Ocheltree",
      "First Name": "Troy",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recWbnPosgBtbD7C2",
    fields: {
      "Last Name": "Oishi",
      "First Name": "Hidekazu",
      "College/Division": ["Agricultural Sciences"],
      "Research Focus": "Japan: President of Maruishi",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1988",
    },
    createdTime: "2021-09-02T14:00:52.000Z",
  },
  {
    id: "recav1B9BAdWqoUGN",
    fields: {
      "Last Name": "Ojima",
      "First Name": "Dennis",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Department of Ecosystem Science and Sustainability"],
      "Research Focus": "Climate Vulnerability of Pastoral ecosystems",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recCmzEK4VOcmVJii",
    fields: {
      "Last Name": "Okawada",
      "First Name": "Akiko",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2008",
    },
    createdTime: "2021-09-02T14:01:29.000Z",
  },
  {
    id: "recOWPvzXVU0K7WLo",
    fields: {
      "Last Name": "Olson",
      "First Name": "Ken",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recAUWyc0RRTiSlfj",
    fields: {
      "Last Name": "Orsi",
      "First Name": "Becky",
      "College/Division": ["OneHealth"],
      "Unit/Program": [
        "Child Maltreatment and Environmental Factors",
        "Colorado focus with applications in other states (rual focus",
        "possibily rual countries).",
      ],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recoFoAb35aKNL0fK",
    fields: {
      "Last Name": "Orton",
      "First Name": "Chris",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Clinical Sciences"],
      "Story Theme": "Health",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recfvHwEyXulkxrtl",
    fields: {
      "Last Name": "Ouchi",
      "First Name": "Shunji",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1983",
    },
    createdTime: "2021-09-02T14:01:48.000Z",
  },
  {
    id: "recE30Qy0rfZsH5k1",
    fields: {
      "Last Name": "Pabilonia",
      "First Name": "Kristy",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recbtGQXlCDXYGM7F",
    fields: {
      "Last Name": "Paustian",
      "First Name": "Keith",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Soil and Crop Sciences"],
      "Research Focus":
        "Sustainable Land Management and Climate Change Mitigation Co-Benefits (SLM-CCMC)",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recNmPgR0rIQggYUq",
    fields: {
      "Last Name": "Pearce",
      "First Name": "Stephen",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Soil and Crop Sciences"],
      "Research Focus":
        "IWYP76FP: Molecular Dissection of Spike Yield Components in Wheat",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recOtlx9PhI2zQEyw",
    fields: {
      "Last Name": "Persch",
      "First Name": "Andrew",
      "College/Division": ["College of Health and Human Sciences"],
      "Research Focus":
        "Collaborating on systematic review of sensory processing assessments. Collaborating on VocFit implementation.",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "reczm5hZu0eBhkqZN",
    fields: {
      "Last Name": "Phillips",
      "First Name": "Cara",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2004",
    },
    createdTime: "2021-09-02T14:02:05.000Z",
  },
  {
    id: "recD2S9K06OT4zH5M",
    fields: {
      "Last Name": "Pidcoke",
      "First Name": "Heather",
      Institution: "Fort Collins",
      "College/Division": ["Office of the Vice President for Research (OVPR)"],
      "Story Theme": "Health",
      "Institutional/Program Stories": ["recyUaYeMecE3kCrS"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recKXiHHJSqDF3fjJ",
    fields: {
      "Last Name": "Pinkayan",
      "First Name": "Shunji",
      "Unit/Program": ["Civil and Environmental Engineering"],
      "Research Focus": "Thailand",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus", "International"],
      "Production Round": "Alumni Round",
      Year: "1983",
      Degree: ["PHD"],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EnVLPAhEljROvz2o6farO7gBlI6gmiFD1DzAkGVhRe5LTw?e=F7DJtb",
    },
    createdTime: "2021-09-02T14:02:15.000Z",
  },
  {
    id: "recruHYjXyf2lMqKS",
    fields: {
      "Last Name": "Platais",
      "First Name": "Gunars",
      "Unit/Program": ["Forest and Rangeland Stewardship"],
      "Research Focus":
        "*Forest and Wood Science; Brazilian, teaching at CU, led Latin American work for World Bank; Former Senior Environment Economist for World Bank",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus", "International"],
      "Production Round": "Potential Story List",
      Year: "1989",
      Degree: ["MS"],
    },
    createdTime: "2021-09-02T14:02:33.000Z",
  },
  {
    id: "rectovsqpzW0WFVyP",
    fields: {
      "Last Name": "Platais",
      "First Name": "Kerri Wright",
      "College/Division": ["Liberal Arts", "Agricultural Sciences"],
      "Unit/Program": ["Social Sciences", "Agronomy"],
      "Research Focus":
        "Head of Intl Ag at Spur; formerly World Bank, Global Crop Trust; International Food Policy Research Institute\n\nShould this be a System story?",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1985, 1989",
      Degree: ["BA", "MS"],
    },
    createdTime: "2021-09-02T14:13:10.000Z",
  },
  {
    id: "recGr4Wgfrnz4VU4l",
    fields: {
      "Last Name": "Rao",
      "First Name": "Sangeeta",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "rec6DlrmUDppCb1Rq",
    fields: {
      "Last Name": "Rasmussen",
      "First Name": "Kristin",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Atmospheric Science"],
      "Research Focus":
        "RELAMPAGO field study: Study of severe convective storms in the lee of the Andes Mountains in central Argentina, which can have devastating impacts in this wine growing region",
      "Spatial Angle": "Cloud Climate interactions",
      "Story Theme": "Environment",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rec6DYmH1UylZTrvX",
    fields: {
      "Last Name": "Rawles",
      "First Name": "Kate",
      "College/Division": ["Liberal Arts"],
      "Unit/Program": ["Philosophy"],
      "Research Focus":
        "Scotland/UK; https://alumline.source.colostate.edu/learning-and-exhorting-to-save-the-environment/",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1990",
      Degree: ["MA"],
    },
    createdTime: "2021-09-02T14:04:36.000Z",
  },
  {
    id: "recP8wJk2RhGyxPpR",
    fields: {
      "Last Name": "Ray",
      "First Name": "Indrakshi",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Computer Science"],
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Spatial Angle": "Computer Science ",
      "Story Theme": "Community",
      "Institutional/Program Stories": ["rec3zF74vfCuxVxlE"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rec7XZs4ZBV0gFJEJ",
    fields: {
      "Last Name": "Raynolds",
      "First Name": "Laura",
      "College/Division": ["College of Liberal Arts"],
      "Unit/Program": ["Sociology"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recPhU5CosdMcxj6U",
    fields: {
      "Last Name": "Reid",
      "First Name": "Robin",
      "StoryMap Link": "https://arcg.is/1jbTXH0",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Ecosystem Science and Sustainability"],
      "Research Focus": "Social Ecological Systems in Africa",
      "Story Title": "Transformation Through Collaboration",
      Tagline: "Science as a catalyst for social change",
      "Research Blurb":
        "CSU Professor Robin Reid works with people in Kenya, Mongolia, and Colorado, applying science to help them address issues that matter most to their communities. A professor in the Department of Ecosystem Science and Sustainability, Reid heads CSU's Center for Collaborative Conservation. She spent 20 years in East Africa, where she developed a process of continuous engagement among landowners, communities, nongovernmental organizations, government, and scientists to address issues ranging from elephant poaching in Africa to wildfire mitigation in the American West.",
      "Blurb Author": "CN",
      "Spatial Angle":
        "Wildfire prevalence in the US. Areas where elephant poaching is the most severe.",
      LAT: " ",
      "Story Theme": "Community",
      "ID Tags": ["Alumnus"],
      "Institutional/Program Stories": ["recbj1fkqfcfxCAHK"],
      "Production Round": "Round 1",
      Year: "1992",
      Degree: ["PHD"],
      "Story Assets": ["Interactive Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EvvKK-2GDB9Hp6DXxAZ8zcwBud0DJybom2Y4GOAf8x4AQg?e=LgAr1f",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recIGZ9Y3bdBvPeg4",
    fields: {
      "Last Name": "Reisfeld",
      "First Name": "Brad",
      "StoryMap Link": "https://arcg.is/1ni01W",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Chemical and Biological Engineering"],
      "Research Focus":
        "chemical pathways for diseases -- research in Thailand on malaria, HIV, etc.",
      "Story Title": "Optimal Dosing",
      Tagline: "Calculating chemical pathways for diseases",
      "Research Blurb":
        "It is not enough to develop a drug to combat disease; scientists must also discover the proper dose. While some of this testing is done on animals, Dr. Brad Reisfeld, professor in the CSU Department of Chemical and Biological Engineering, saw a different way — a mathematical approach, modeling biological systems and chemical pathways to better understand the effects of drugs on humans and animals. Dr. Reisfeld's research has been used to optimize dosing for pulmonary tuberculosis, as well as several diseases important in Thailand such as malaria, HIV, and Steven-Johnson Syndrome.",
      "Blurb Author": "JF",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Story Theme": "Health",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "receFeiLLgASJQW6j",
    fields: {
      "Last Name": "Rijsberman",
      "First Name": "Frank",
      "Research Focus": "Korea, heads GGGI in Seoul",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T14:06:02.000Z",
  },
  {
    id: "recf1WcRrDF5VukmN",
    fields: {
      "Last Name": "Ryan",
      "First Name": "Elizabeth",
      "StoryMap Link": "https://arcg.is/1GCbPv0",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Environmental and Radiological Health Sciences"],
      "Research Focus": "Nutrition - Mali ",
      "Story Title": "One Bran of Rice",
      Tagline: "Eating grains to improve gut health",
      "Research Blurb":
        "The human gut contains tens of trillions of microorganisms, and these bacteria interact intimately with the immune system. The food that we eat impacts which bacteria are present and can ultimately reduce the risk of developing cancer and infectious disease. Dr. Elizabeth Ryan studies one of the world’s most abundant foods — rice — and its potential role in both modulating gut health to reduce disease, and increasing food security in lower- and middle-income countries. Ryan works in many countries but is starting a new project with the International Rice Research Institute in the Philippines, characterizing the way rice byproducts like rice bran can be used to improve global health and food security.",
      "Blurb Author": "AF",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Spatial Angle": "Map of major rice crops in the US ",
      "Story Theme": "Health",
      "Production Round": "Round 1",
      "Story Assets": ["Video "],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EnSSeavNPCBIspwxoOPmVfQByJuXKRp8098nLUMmvnzxJQ?e=dtGzgQ",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recLReJHeIJ09IUcC",
    fields: {
      "Last Name": "Saito",
      "First Name": "Sawaka",
      "Unit/Program": ["Occupational Therapy"],
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Degree: ["MS"],
    },
    createdTime: "2021-09-02T14:06:50.000Z",
  },
  {
    id: "recvb9iW2t7gjP7e9",
    fields: {
      "Last Name": "Salerno",
      "First Name": "Jonathan",
      "StoryMap Link": "https://arcg.is/LDmSy",
      "Production Phase": "Story Edits",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Human Dimensions of Natural Resources"],
      "Research Focus":
        "Climate Change, Food Security, Human-Elephant Conflict - Uganda",
      "Story Title": "Adapting to Nature",
      Tagline: "How do you respond to a changing environment?",
      "Research Blurb":
        "Jonathan Salerno, new to CSU, is an ecologist in the Department of Human Dimensions of Natural Resources studying how and why humans make decisions, particularly in response to environmental changes. Salerno’s work tries to better understand human behavior in the context of biodiversity conservation and natural resource management. One of his current research projects focuses on human-elephant interactions, mostly through crop depredation, in southern Africa, and people adapt to negative impacts to support food security.",
      "Blurb Author": "CRM",
      "Centroid Mapper": "Amanda Hastings (2021-2022)",
      "Spatial Angle":
        "How the heck can we map human-elephant interactions and food security?? Let's do it. \n\nContact about sharing .shp of boundary that was mentioned in email response to Lauren (see sharepoint)\n\nTungamalenga, Iringa Region, Tanzania (-7.834614, 35.096288).",
      LAT: " ",
      "Story Theme": "Food",
      "ID Tags": ["Alumnus"],
      "Production Round": "Round 1",
      "Grand Challenge": ["Climate Change"],
      "Story Assets": ["Interactive Map", "Find Existing Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "Career Pathway ": ["Ecologist"],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EntAkyqE8whAoeo2aTGoYIsBR1WqaQmzF_Ksx4hwmQhkMQ?e=rH3ddL",
      "StoryMap VIEW Link":
        "https://storymaps.arcgis.com/stories/75bf20a63f144919bbb76cc504ee9a6d/edit",
      "Story Card Image": [
        {
          id: "atti3to2WXKkAMc8u",
          width: 1156,
          height: 726,
          url: "https://dl.airtable.com/.attachments/89bd4160623b10839f3805f18bd81984/07e60039/2018-106-1-34-salerno-3-figcap.jpeg",
          filename: "2018-106-1-34-salerno-3-figcap.jpeg",
          size: 247099,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/b3e36cbbb401a4f4f2fd41e5ae3ce3d3/1730a9b3",
              width: 57,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/6e98165447636e1c91953c25c23f4e70/d57e543a",
              width: 815,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/fc6b6bd51bc88eb013a56c06c8fb0f4c/a3725c4a",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      "Pop-Up Card Content":
        "Farmers, livestock keepers, and rural resource users around the world will increasingly need to adapt to changes in climate.",
      "Pop-Up Card Image": [
        {
          id: "attHF2nQMJCiPAa1K",
          width: 830,
          height: 400,
          url: "https://dl.airtable.com/.attachments/25c14edd78fd7920068fd54c7ab09cc1/e6538445/2018-106-1-34-salerno-9-artfig.jpeg",
          filename: "2018-106-1-34-salerno-9-artfig.jpeg",
          size: 148822,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/409ca04f38edc4221fa0b4c3dbc14923/2a47006b",
              width: 75,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/cbe116e81000910dc1deaf6b91ec541a/ec033eff",
              width: 830,
              height: 400,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/57cdd911818987a7da07888ef67aa0d8/3db58bde",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recWKSGyqiXamrGqo",
    fields: {
      "Last Name": "Salkeld",
      "First Name": "Dan",
      "College/Division": ["OneHealth"],
      "Unit/Program": ["Tanzania", "Africa"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recHufq9XGfh2xbSK",
    fields: {
      "Last Name": "Salman",
      "First Name": "Mo",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Clinical Sciences"],
      "Research Focus":
        "CSU- Animal Population Animal Health Institute (APHI) is a reference center for FAO in animal disease surveillance and epidemiology.",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Spatial Angle": "infectious diseases",
      "Story Theme": "Food",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rec4sVHHQevn8sZlt",
    fields: {
      "Last Name": "Schneider",
      "First Name": "Lindsey",
      Institution: "Fort Collins",
      "College/Division": ["Liberal Arts"],
      "Unit/Program": ["Ethnic Studies"],
      "Story Theme": "Environment",
      "Story Tags": ["Environmental Justice", "Community Health"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recPD4P9h7mWmFDt8",
    fields: {
      "Last Name": "Schountz",
      "First Name": "Tony",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Microbiology, Immunology, and Pathology"],
      "Story Theme": "Health",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recGMsld5XqadURHA",
    fields: {
      "Last Name": "Schumacher",
      "First Name": "Russ",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Atmospheric Science"],
      "Research Focus":
        "RELAMPAGO field study: Study of severe convective storms in the lee of the Andes Mountains in central Argentina, which can have devastating impacts in this wine growing region",
      "Research Blurb":
        "What conditions are most conducive to extreme local rainfall? What processes determine whether a storm will produce a large amount of rain in a small area vs. a small amount spread among a large area? How can we improve our forecasting of heavy rain events? Knowing where it is going to rain, for how long, and how hard is the key to understanding everything from agriculture to flooding. And these questions are at the forefront of Dr. Russ Schumacher's work as the Colorado State Climatologist and leader of the CSU-based Colorado Climate Center.",
      "Blurb Author": "JF",
      "Spatial Angle": "Mesoscale meteorology - severe weather?",
      "Story Theme": "Environment",
      "ID Tags": ["Alumnus"],
      "Production Round": "Round 2",
      "Grand Challenge": ["Climate Change"],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recUm6ubbDoXTAglk",
    fields: {
      "Last Name": "Scorza",
      "First Name": "Andrea",
      "College/Division": ["One Health"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recO0AFxNBHr6Ge47",
    fields: {
      "Last Name": "Seidl",
      "First Name": "Andrew",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Agricultural and Resource Economics"],
      "Research Focus":
        "Climate Adaptation and Mitigation through Biodiversity Investment Opportunities (CAMBIO), French National Research Agency (ANR). Teaching/Research Fulbright Scholar Award at the Central American Institute for Business Administration (INCAE), Costa Rica. Co-taught MS course in sustainability economics and management. Gave seminars on biodiversity economics, sustainable tourism and management and economic development. Contributed to the development of a scholarly exchange of students and faculty between CSU and Uni Trento.",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recJwDttQHc7WFJfv",
    fields: {
      "Last Name": "Shackelford",
      "First Name": "Chuck",
      "College/Division": ["Walter Scott", "Jr. College of Engineering"],
      "Unit/Program": ["CEE"],
      "Research Focus":
        "Chuck can discuss past and present international water initiatives that may be relevant to this international agriculture effort",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recaNvFnFzNfDhTLK",
    fields: {
      "Last Name": "Sharvelle",
      "First Name": "Sybil",
      "StoryMap Link": "https://arcg.is/eL9nH",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Civil and Environmental Engineering"],
      "Research Focus": "Gray Water - Global Focus ",
      "Story Title": "Something in the Urban Water",
      Tagline: "Conserving greywater and stormwater for reuse",
      "Research Blurb":
        "Without water, there is no life — and every drop counts. Sybil Sharvelle, Ph.D., associate professor of civil and environmental engineering at CSU, is researching water conservation systems such as graywater and stormwater reuse in urban and arid environments. In 2018, Sharvelle and her team secured a $3 million NSF grant to develop a national traineeship program to train the next generation of scientific leaders “to tackle complex societal programs.” The program — InTERFEWS (Interdisciplinary Training, Education and Research in Food-Energy-Water Systems in Semi-Arid Regions) — taps the skills and interests of Ph.D. students from disparate disciplines to research innovations that foster a more sustainable, waste-free future for all.",
      "Blurb Author": "CRM",
      LAT: " ",
      "Story Theme": "Water",
      "Production Round": "Round 1",
      "Story Assets": ["Video "],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/Ektq0xJZgehEjeUxgEl5fwIBZ_PNIJNlLTvjXyNZM2rD1w?e=7ihpcw",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rec2C8HZg5NTGgaig",
    fields: {
      "Last Name": "Sherif",
      "First Name": "Merall",
      "StoryMap Link": '"Building a World"',
      Institution: "Fort Collins",
      "Research Focus":
        "Women in Science; Poet\nhttps://cvmbs.source.colostate.edu/slam-poet-writes-building-a-world-poem-for-women-in-science-symposium/",
      "Story Theme": "Community",
      "ID Tags": ["Student Researcher", "Alumnus"],
      "Story Tags": ["Civic Engagement"],
      "Production Round": "Round 3",
    },
    createdTime: "2021-09-03T13:42:23.000Z",
  },
  {
    id: "recSpRL7Zcgc279EB",
    fields: {
      "Last Name": "Simske",
      "First Name": "Steve",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Systems Engineering"],
      "Research Focus": "International supply chains and illicit trade",
      "Research Blurb":
        "Underground networks traffic in everything from illegal weapons and drugs to looted antiquities to exotic animal products or even human beings. These networks are often highly technologically sophisticated and operate with impunity across borders, funneling profits to criminal and terrorist organizations, undermining governments, and victimizing marginalized people. CSU engineering professor Steve Simske wants to help put an end to all that. Between 2008-2012, Dr. Simske pioneering a counterfeit image-detection technology at HP. Through added customization and analytic capabilities, Simske hopes this technology can monitor various supply chains and scan for statistically relevant deviations in order to differentiate legitimate and illicit supply chains. ",
      "Blurb Author": "JF",
      "Spatial Angle": "Illicit Trade Map",
      "Story Theme": "Community",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recphEQVYStiLqQuJ",
    fields: {
      "Last Name": "Solomon",
      "First Name": "Jen",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Human Dimensions of Natural Resources"],
      "Research Focus":
        "Dr. Jennifer Solomon’s research focuses on the interface of development, livelihoods and collaborative resource management in communities adjacent to protected areas. She has evaluated integrated conservation and development projects in Latin America and East Africa. She also develops and tests innovative social science research methods for assessing non-compliance with resource regulations. In the past years she has started new research efforts focused on the human dimensions of the lionfish invasion as well as women in conservation leadership. ",
      "Spatial Angle":
        "Lionfish observations (potentially- depending on the content of the research highlighted in the story map)",
      "Story Theme": "Community",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "reck1wabMdFzlPAqP",
    fields: {
      "Last Name": "Sonu",
      "First Name": "Jungho",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T14:08:36.000Z",
  },
  {
    id: "recyHdRJlQs754WWW",
    fields: {
      "Last Name": "Stockman",
      "First Name": "Jonathan",
      "College/Division": ["OneHealth"],
      "Unit/Program": [
        "Diet of Pets",
        "Why is your pet fat? (New York Times article)",
      ],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recUO7PtWaPa4U3EQ",
    fields: {
      "Last Name": "Stonaker",
      "First Name": "Frank",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recHLYMy7nuyIU0ij",
    fields: {
      "Last Name": "Tahtamouni",
      "First Name": "Luna",
      "College/Division": ["Natural Sciences"],
      "Research Focus": "Zarqa, Jordan -- Assoc Prof. Hashemite Univ.",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2005",
      Degree: ["PHD"],
    },
    createdTime: "2021-09-02T14:08:48.000Z",
  },
  {
    id: "rec5UVxUS35oIamyn",
    fields: {
      "Last Name": "Takagi",
      "First Name": "Makiko",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2007",
    },
    createdTime: "2021-09-02T14:09:32.000Z",
  },
  {
    id: "recNLv0ZbMtrescgM",
    fields: {
      "Last Name": "Takagi",
      "First Name": "Yumiko",
      "Research Focus": "Japan: Kagawa University",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1994",
    },
    createdTime: "2021-09-02T14:09:49.000Z",
  },
  {
    id: "rec0mmhB6EaRNGida",
    fields: {
      "Last Name": "Takano",
      "First Name": "Yohei",
      "Unit/Program": ["Atmospheric Science"],
      "Research Focus": "From Japan: Postdoc at Los Alamos",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus", "International"],
      "Production Round": "Potential Story List",
      Year: "2011",
      Degree: ["MS"],
    },
    createdTime: "2021-09-02T14:10:11.000Z",
  },
  {
    id: "reci0BdW83dKPJP3C",
    fields: {
      "Last Name": "Teel",
      "First Name": "Tara",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["Human Dimensions of Natural Resources"],
      "Research Focus":
        "Human - wildlife conflict in India Dr. Teel's work focuses on improving conservation decision-making through understanding human thought and behavior and through building social science capacity among conservation professionals. Much of her research has been devoted to examining human-wildlife relationships in the U.S. and globally, with a particular focus on employing concepts and methodologies from social psychology to study human values toward wildlife, attitudes toward wildlife-related issues, and the social factors underlying human-wildlife conflict. https://warnercnr.colostate.edu/person/?user=zXLRUnfFEzEGjJEqWYGUMg%3D%3D",
      "Spatial Angle": "Human-Wildlife Conflict Incident Map",
      "Story Theme": "Environment",
      "ID Tags": ["Alumnus"],
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rechvOX6RLPvWLcEv",
    fields: {
      "Last Name": "Theis",
      "First Name": "David",
      "College/Division": ["Liberal Arts"],
      "Unit/Program": ["English"],
      "Research Focus":
        "US -- Chief of Media for the World Bank -- Washington DC",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "1989",
      Degree: ["BA"],
    },
    createdTime: "2021-09-02T14:11:18.000Z",
  },
  {
    id: "recVqh3plVwYps3sc",
    fields: {
      "Last Name": "Thilmany",
      "First Name": "Dawn",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Agricultural and Resource Economics"],
      "Story Theme": "Food",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rectvw1TwSpi6nmVe",
    fields: {
      "Last Name": "Thomas",
      "First Name": "Milton",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Animal Sciences"],
      "Research Focus":
        "Genomic analyses of thermotolerance in Holstein Dairy cattle managed during summer in Southern Sonora Mexico, UC-MEXUS of CONACYT of Mexico. Border State beef production efficiency in Mexico and the United States, CONACYT",
      "Spatial Angle": "Density of Dairy Cattle in the US",
      "Story Theme": "Food",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recvtgBqIn1Tf6ADU",
    fields: {
      "Last Name": "Tomita",
      "First Name": "Makiko",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2004",
    },
    createdTime: "2021-09-02T14:12:17.000Z",
  },
  {
    id: "recI6EOzKkaS5OOB4",
    fields: {
      "Last Name": "Trivedi",
      "First Name": "Pankaj",
      Institution: "Fort Collins",
      "College/Division": ["Agricultural Sciences"],
      "Unit/Program": ["Agricultural Biology"],
      "Research Focus":
        "Sugarcane Research Australia. Advice on managing plant diseases particularly Yellow Canopy Syndrome",
      "Story Theme": "Environment",
      "Production Round": "Round 2",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recYPvLwzzDgpVWzq",
    fields: {
      "Last Name": "Tsao",
      "First Name": "Dean",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-02T14:12:34.000Z",
  },
  {
    id: "recSzadl36ySwI4D0",
    fields: {
      "Last Name": "Uchanski",
      "First Name": "Mark",
      "College/Division": ["College of Agricultural Sciences"],
      "Unit/Program": ["Horticulture and Landscape Architecture"],
      "Research Focus":
        "Administracion de Proyecto en Innovacion Agroalimentaria, Government of Mexico",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recgwokagbeoAF5V4",
    fields: {
      "Last Name": "Uematsu",
      "First Name": "Sohei",
      "Story Theme": "Int'l/FG/Alum/Student",
      "ID Tags": ["Alumnus"],
      "Production Round": "Potential Story List",
      Year: "2007",
    },
    createdTime: "2021-09-02T14:12:43.000Z",
  },
  {
    id: "recAGSl7reCFvxLQg",
    fields: {
      "Last Name": "VandeWoude",
      "First Name": "Sue",
      "StoryMap Link": "https://arcg.is/0XvCDS",
      "Production Phase": "Story Edits",
      Institution: "Fort Collins",
      "College/Division": ["Veterinary Medicine and Biomedical Sciences"],
      "Unit/Program": ["Microbiology, Immunology, and Pathology"],
      "Research Focus": "Disease ecology/widlife disease in Australia/Tasmania",
      "Story Title": "Feline Infections",
      Tagline: "Reducing viruses in domestic cats",
      "Research Blurb":
        "All cats — domestic and wild — can become infected with feline immunodeficiency virus (FIV), resulting in a disease process comparable to HIV in humans. CSU veterinarian Dr. Sue VandeWoude’s laboratory studies factors that contribute to FIV transmission and the development and progression of the disease in cats. The ultimate goal of this research is to translate these findings to better understand viruses in humans. Dr. VandeWoude is currently on a Fulbright sabbatical studying wildlife disease ecology in Tasmania.",
      "Blurb Author": "EKA",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      LAT: " ",
      "Story Theme": "Health",
      "Institutional/Program Stories": [
        "recPQTwK0Bc7NsocO",
        "rec0scLExpYcBzVhl",
      ],
      "Production Round": "Round 1",
      "Grand Challenge": ["Infectious Disease"],
      "Story Assets": ["TBD"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "Career Pathway ": ["Veterinarian", "Virologist "],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EhE_UDsdjvFMkrjcBZWTjwABvlQqz_zg31jBTV60cBmKcQ?e=eFKuMG",
      "StoryMap VIEW Link":
        "https://storymaps.arcgis.com/stories/1ae6356047b143ae927111e9e4f3fed0/edit",
      "Story Card Image": [
        {
          id: "attnJBsPsjETZyMMK",
          width: 6000,
          height: 3375,
          url: "https://dl.airtable.com/.attachments/fcdb726c505759c243af3ccb477d397b/750cb545/nataliya-smirnova-rayvpOMVwJM-unsplash1.jpg",
          filename: "nataliya-smirnova-rayvpOMVwJM-unsplash (1).jpg",
          size: 2852397,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/c2838390f648baad813f926152f9783e/215d72d0",
              width: 64,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/16825574e593a2fa8b73f608ca77208c/d4e41cdc",
              width: 910,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/9e9b4b88bda667997d60ae67cc41c87d/4a9cf9a8",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      "Pop-Up Card Content":
        "All cats — domestic and wild — can become infected with feline immunodeficiency virus (FIV), resulting in a disease process comparable to HIV in humans. ",
      "Pop-Up Card Image": [
        {
          id: "att7RZ71TQnfB1W8V",
          width: 4774,
          height: 3183,
          url: "https://dl.airtable.com/.attachments/2a84a70fe4f3fddcd4b775aefd9c4881/deece579/paul-hanaoka-w2DsS-ZAP4U-unsplash.jpg",
          filename: "paul-hanaoka-w2DsS-ZAP4U-unsplash.jpg",
          size: 1292768,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/b3cd96eed44e0f247685dc0a7ee6e20a/e848b3d4",
              width: 54,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/35931d2579b2471001222a04b1f3a06c/e2b2383a",
              width: 768,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/d13d6884e7d9b39176c42b3a4bb53d21/2ecc6c3c",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recC9N2eFPItC98Vx",
    fields: {
      "Last Name": "Velasco",
      "First Name": "Marcela",
      "College/Division": ["SOGES"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recZ67E5oRnmkdg2i",
    fields: {
      "Last Name": "Venayagamoorthy",
      "First Name": "Karan",
      "College/Division": ["Walter Scott", "Jr. College of Engineering"],
      "Unit/Program": ["CEE"],
      "Research Focus":
        "Effects of aquaculture wastes on coastal water quality, and improving efficiency of small drinking water systems.",
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recvyevG82galuqu4",
    fields: {
      "Last Name": "Venkatachalam",
      "First Name": "Chandra",
      "StoryMap Link": "https://arcg.is/04mn8v",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": ["Electrical and Computer Engineering"],
      "Research Focus": "Radar observation - Space",
      "Story Title": "Sensing Storms With Radar",
      Tagline: "Saving lives from the world's most extreme weather",
      "Research Blurb":
        'V. "Chandra" Chandrasekaran, professor of Electrical and Computer Engineering at CSU, is one of the world\'s leading experts in geoscience and remote sensing — a field that uses data from satellites to advance understanding of the land, oceans, atmosphere, and space. His work with meteorological radar systems has led to technologies that protect lives and improve weather forecasting all over the world — including Finland, where he was knighted by the government for his international work.',
      "Blurb Author": "CN",
      "Centroid Mapper": "Mary Williams (2021-2022)",
      "Spatial Angle":
        "Locations with severe hurricanes and tornados: If this exists, let's not recreate it.",
      LAT: "40",
      LONG: "-105",
      "Story Theme": "Environment",
      "ID Tags": ["Alumnus"],
      "Institutional/Program Stories": [
        "rec4ydfnP0CQNy7EY",
        "rec0scLExpYcBzVhl",
      ],
      "Production Round": "Round 1",
      Year: "1983, 1996",
      Degree: ["MS", "PHD"],
      "Story Assets": ["Find Existing Map"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/EoI94Ka59KdAjQYOW-WcHUEBm5PyXUOwUhxwfdqLebhZrg?e=CDEXu4",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "recDSyp4JqtnoTOls",
    fields: {
      "Last Name": "Wall",
      "First Name": "Diana",
      "StoryMap Link": "https://arcg.is/eSHrq",
      Institution: "Fort Collins",
      "College/Division": ["Warner College of Natural Resources"],
      "Unit/Program": ["School of Global Environmental Sustainability"],
      "Research Focus": "Soil Nematode Diversity - Antarctica",
      "Story Title": "The Secret Life of Soil",
      Tagline: "Unearthing microscopic fertility in Antarctica",
      "Research Blurb":
        "In Antarctica, the frozen ground looks barren – but dig into it, and put it under a microscope, and you’ll see tiny rugged worms, nematodes, that could help unlock our understanding of Earth’s changing climate. CSU professor Diana Wall has been making the voyage to the bottom of the globe every year since 1989 — more than 30 years of studying the life hidden in the Antarctic soil. Exploring the soil, studying the diversity of microbes and invertebrates, can shed light on how human activities around the world affect the health, productivity, and fertility of soils worldwide.",
      "Blurb Author": "MH",
      LAT: "-69",
      LONG: "45",
      "Story Theme": "Environment",
      "Institutional/Program Stories": ["rec0scLExpYcBzVhl"],
      "Production Round": "Round 1",
      "Story Assets": ["VR"],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/Et6Fu6vEOKtOg25Fcg3jl5QBLYlME9_ZhoHr7K3dTwBidw?e=sfKQYJ",
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
  {
    id: "rectzR1Z2jm3ivR8d",
    fields: {
      "Last Name": "Webb",
      "First Name": "Colleen",
      "College/Division": ["CVMBS"],
      "Production Round": "Potential Story List",
    },
    createdTime: "2021-09-21T23:26:45.000Z",
  },
  {
    id: "recGgW5LWUxi3xVXr",
    fields: {
      "Last Name": "Willson",
      "First Name": "Bryan",
      "StoryMap Link": "https://arcg.is/10amC8",
      "Production Phase": "Story Edits",
      Institution: "Fort Collins",
      "College/Division": ["Walter Scott, Jr. College of Engineering"],
      "Unit/Program": [
        "Energy Institute; Engines & Energy Conversion Laboratory",
      ],
      "Research Focus": "Energy - Rwanda",
      "Story Title": "Electric Villages",
      Tagline: "Harnessing clean and affordable energy in Rwanda",
      "Research Blurb":
        "Electric power is scarce in Rwanda, where 1-in-4 people has an electric hookup, a hookup rate that drops to 1-in-10 in rural areas. CSU professor Bryan Willson’s work harnessing the University’s energy expertise to bring clean, affordable energy to Rwanda is just one example of Willson’s 25 years of work in more than 40 countries. The teams in Willson’s research lab, the Engines and Energy Conversion Lab are innovators in world needs like energy production and engine technology, advanced electrical grids, and biofuels. In Rwanda, AC/DC microgrids are powering people’s daily lives and boosting the entire country’s economic wellbeing.",
      "Blurb Author": "MH",
      LAT: " ",
      "Story Theme": "Energy",
      "Institutional/Program Stories": ["recz5lIQrJxWz00es"],
      "Production Round": "Round 1",
      "Story Assets": ["Video "],
      "Start date": "2021-07-01",
      "End date": "2021-10-01",
      "Career Pathway ": ["Mechanical Engineer"],
      "SharePoint Folder":
        "https://colostate.sharepoint.com/:f:/s/CAS_Global_Mapping_and_Strategic_Outreach/ErxaYiq2heNOjLA5nqUQS_sB3uiJsH8asKKzlXoQQTNQsQ?e=nhq5yk",
      "StoryMap VIEW Link":
        "https://storymaps.arcgis.com/stories/2664526930e648fd91223fd64b8ea50f",
      "Story Card Image": [
        {
          id: "attEbUWapNcJNo0LE",
          width: 2048,
          height: 700,
          url: "https://dl.airtable.com/.attachments/dbe2ccb66a6806a6d8dc9419a854946f/dfc6077a/cover5.jpeg",
          filename: "cover5.jpeg",
          size: 385645,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/033441fe13bb5efd46ebe570b3dcdf60/de4fb81c",
              width: 105,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/e5553d1e561f3bedb5a6b6fb2ad269af/47c38671",
              width: 1498,
              height: 512,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/80e69db88fc69d71301c1787ac5c2f0b/9c560ce8",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
      "Pop-Up Card Content":
        "Electric power is scarce in Rwanda, where 1-in-4 people have an electric hookup, a hookup rate that drops to 1-in-10 in rural areas.",
      "Pop-Up Card Image": [
        {
          id: "attqjuw1tmdW5OIQe",
          width: 4000,
          height: 6000,
          url: "https://dl.airtable.com/.attachments/7e54a9df3196dbfcdf3d6c1c966c3983/0ddc8b79/david-leveque-54vXtfOpR1Q-unsplash.jpg",
          filename: "david-leveque-54vXtfOpR1Q-unsplash.jpg",
          size: 322336,
          type: "image/jpeg",
          thumbnails: {
            small: {
              url: "https://dl.airtable.com/.attachmentThumbnails/331a498fce249e24a49a61fad34cc848/3973bc57",
              width: 24,
              height: 36,
            },
            large: {
              url: "https://dl.airtable.com/.attachmentThumbnails/3036ddff1737c7a807fbe4641b32577d/db88c0ea",
              width: 512,
              height: 768,
            },
            full: {
              url: "https://dl.airtable.com/.attachmentThumbnails/260da04e55432e9ace5f9ebf54f7d0d8/41c8958a",
              width: 3000,
              height: 3000,
            },
          },
        },
      ],
    },
    createdTime: "2021-08-29T20:38:35.000Z",
  },
];
